apiVersion: v1
kind: Service
metadata:
  name: my-kube3-service  # Updated service name
spec:
  type: LoadBalancer  # Exposes the service externally
  selector:
    app: my-kube-app1  # This must match the app label in your deployment
  ports:
    - protocol: TCP
      port: 8082  # External port to access the app
      targetPort: 3000  # Port on the container (Node.js app is listening here)
