apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-kube3-deployment
  labels:
    app: my-kube-app1
spec:
  replicas: 2  # Number of replicas
  selector:
    matchLabels:
      app: my-kube-app1
  template:
    metadata:
      labels:
        app: my-kube-app1
    spec:
      containers:
        - name: my-kube3-container
          image: docker.io/pravalika7/my-kube3-chinna:latest  # Updated Docker image
          ports:
            - containerPort: 3000  # Ensure this matches your app's port
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
          env:
            - name: NODE_ENV
              value: "production"
